# Generated by Django 4.0.4 on 2023-09-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_token',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
